spring:
  profiles:
    active: default
  application:
    name: companies-crud
  config:
    import: "optional:configserver:http://localhost:7777"
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection:
        timeout: ${spring.datasource.hikari.connection.timeout}
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
    url: ${spring.datasource.url}
management:
  endpoints:
    web:
      exposure:
        include: '*'
open:
  api:
    server:
      url: http://localhost:${server.port}
      description: Local
    contact:
      info:
        url: www.test.com
        name: Maximiliano R Soria
        title: Companies API
        email: MaximilianoRSoria@gmail.com
        description: It is Company API
    context:
      path: ${server.servlet.context-path}
    licence:
      name: Apache 2.0
      url: https://springdoc.org
    external:
      doc:
        url: www.docs.com
        description: Find more
    info:
      build:
        version: 1.0.0

  application:
    name: companies-crud
springdoc:
  api-docs:
    path: /api-docs
server:
  port: '8081'
  servlet:
    context-path: /companies-crud
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

eureka:
  instance:
    instance-id: '${spring.application.name}:${random.value}'
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
