spring:
  application:
    name: config-server
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaximilianoRodrigoSoria/microservices-configs.git
          username: MaximilianoRodrigoSoria
          password: ${GIT_TOKEN}
          default-label: master
          clone-on-start: true
server:
  port: 7777


eureka:
  instance:
    instance-id: '${spring.application.name}:${server.port}'
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/